Jenkinsfile, ogc/common/core/templates/conformance.go.html, ogc/common/core/templates/conformance.go.json, renovate.json
https://dev.kadaster.nl/jira/browse/PDOK-15263
=> conformance improvements

engine/config.go
https://dev.kadaster.nl/jira/browse/PDOK-15305
=> Fix minor error in config

assets/css/gokoala.css, assets/swagger-ui/swagger-ui-pdok.css, engine/config.go, engine/engine.go, engine/engine_test.go, engine/template.go, engine/templates/layout.go.html, examples/config_3d.yaml, examples/config_multiple_ogc_apis_single_collection.yaml, examples/config_vectortiles.yaml, ogc/common/core/main.go, ogc/common/core/templates/conformance.go.html, ogc/common/core/templates/landing-page.go.html, ogc/common/geospatial/main.go, ogc/common/geospatial/templates/collection.go.html, ogc/common/geospatial/templates/collections.go.html, ogc/styles/main.go, ogc/styles/templates/styleMetadata.go.html, ogc/styles/templates/styles.go.html, ogc/tiles/main.go, ogc/tiles/templates/tileMatrixSets.go.html, ogc/tiles/templates/tiles.go.html
https://dev.kadaster.nl/jira/browse/PDOK-15355
- Refactor
=> Extend navbar with breadcrumb path and JSON link

examples/config_3d.yaml, examples/config_multiple_ogc_apis_single_collection.yaml
=> Fix 3D examples

engine/templates/openapi/preamble.go.json
=> Disable markdown in OpenAPI (revert)

README.md, engine/engine.go, engine/templates/layout.go.html, examples/config_processes.yaml
aanpassingen tbv OGC API Processes
- GoKoala baseurl doorgeven aan requesten die geproxied worden, tbv opbouwen absolute url's in responses van OGC API Processes
- Dataset breadcrumb verwijderd uit de html layout template voor OGC API Proccesses
=> Ogc api processes optimizations

ogc/tiles/templates/tiles/NetherlandsRDNewQuad.go.html, ogc/tiles/templates/tiles/WebMercatorQuad.go.html, webcomponents/vectortile-view-component/README.md, webcomponents/vectortile-view-component/src/app/app.component.ts, webcomponents/vectortile-view-component/src/app/mapprojection.ts, webcomponents/vectortile-view-component/src/index.html
Added style url and debug grid functionality in map web-component 
https://dev.kadaster.nl/jira/browse/PDOK-15391
=> Pdok 15391 tile url and grid

assets/css/gokoala.css, engine/config.go, ogc/common/core/templates/api.go.html, ogc/common/core/templates/landing-page.go.html, ogc/common/geospatial/templates/collections.go.html
=> Fix table layout on landing page and api page + add lastUpdatedBy field

engine/config.go, engine/openapi_test.go, engine/templates/layout.go.html, examples/config_3d.yaml, examples/config_multiple_ogc_apis_single_collection.yaml, examples/config_vectortiles.yaml, ogc/styles/main_test.go
=> Implement datasets link

ogc/common/core/templates/conformance.go.html
=> Remove url's for all draft conformance classes

ogc/tiles/main_test.go, ogc/tiles/templates/tiles.go.html
ogc tiles
https://dev.kadaster.nl/jira/browse/PDOK-15386
=> PDOK-15386

engine/templates/layout.go.html, ogc/styles/templates/styles.go.html, ogc/tiles/templates/tiles.go.html
=> Load vector-tile-viewer only when required, not on landing page.

ogc/common/geospatial/templates/collection.go.json
=> Fix URLs in collection JSON

assets/i18n/active.en.toml, assets/i18n/active.nl.toml, engine/templates/layout.go.html, examples/config_3d.yaml, ogc/common/core/templates/api.go.html, ogc/common/core/templates/conformance.go.html, ogc/common/geospatial/templates/collections.go.html, ogc/styles/templates/styles.go.html, ogc/tiles/templates/tiles.go.html
=> Various small language fixes

ogc/tiles/templates/tiles.go.html, webcomponents/vectortile-view-component/src/app/app.component.ts
- Update vectortile-view wanneer `tile-url` geüpdated wordt
- Kleine wijzigingen aan script in `tiles.go.html`
- Bugfix
- Refactor
=> Small fix for tiles vector-view

engine/config.go, engine/engine.go, engine/i18n.go, engine/openapi.go, engine/template.go, engine/templates/layout.go.html, ogc/common/core/main_test.go, ogc/common/core/templates/api.go.html, ogc/common/core/templates/conformance.go.html, ogc/common/core/templates/landing-page.go.html, ogc/common/geospatial/main_test.go, ogc/common/geospatial/templates/collection.go.html, ogc/common/geospatial/templates/collections.go.html, ogc/styles/main_test.go, ogc/styles/templates/styleMetadata.go.html, ogc/styles/templates/styles.go.html, ogc/tiles/main_test.go, ogc/tiles/templates/tileMatrixSets.go.html, ogc/tiles/templates/tiles.go.html, ogc/tiles/templates/tiles/EuropeanETRS89_GRS80Quad_Draft.go.html, ogc/tiles/templates/tiles/NetherlandsRDNewQuad.go.html, ogc/tiles/templates/tiles/WebMercatorQuad.go.html
=> Optimize i18n: remove need to specify language in template.

engine/config.go, examples/config_3d.yaml
=> Make email optional

ogc/tiles/main.go
=> Allow HEAD requests on vector tiles

assets/i18n/active.en.toml, assets/i18n/active.nl.toml, ogc/common/core/templates/api.go.html, ogc/common/core/templates/landing-page.go.html
=> Name change: use OpenAPI instead of just API

ogc/geovolumes/main.go, ogc/geovolumes/main_test.go
https://dev.kadaster.nl/jira/browse/PDOK-15660
- Bugfix
=> Add support for explicit tiling JSON files in 3d geovolumes routing

assets/i18n/active.en.toml, assets/i18n/active.nl.toml, engine/templates/openapi/README.md, engine/templates/openapi/styles.go.json, ogc/common/core/main.go
https://dev.kadaster.nl/jira/browse/PDOK-15654
-
=> Polishing + remove resources endpoint from OAS

assets/i18n/active.en.toml, assets/i18n/active.nl.toml, engine/templates/layout.go.html, ogc/common/core/templates/landing-page.go.html, ogc/styles/templates/styles.go.html
=> Polishing text/translations on various pages

README.md, ogc/tiles/templates/tiles.go.html
=> Display correct X/Y in example URL based on selected CRS.

ogc/geovolumes/main.go
Support explicit call to layer.json
=> Support explicit call to layer.json

viewer/cypress/feature-view-pdok-rd.cy.ts
=> repair failing cypress test

engine/config.go, ogc/features/templates/feature.go.html, ogc/features/templates/features.go.html, viewer/cypress/fixtures/collectionresponse.json, viewer/src/app/feature-view/feature-view.component.ts, viewer/src/index.html
Rollback HTML changes of https://github.com/PDOK/gokoala/pull/89 + fix regression in viewer (NPE)
=> Rollback https://github.com/PDOK/gokoala/pull/89 + fix viewer

README.md, engine/config.go, main.go, ogc/styles/main.go
=> Fix incorrect styles URL in HTML view

ogc/features/templates/features.go.html
https://dev.kadaster.nl/jira/browse/PDOK-15919
- Refactor
=> Styling fix

engine/engine.go, engine/engine_test.go, engine/openapi.go, ogc/features/datasources/geopackage/asserts.go, ogc/features/datasources/geopackage/geopackage.go, ogc/features/datasources/geopackage/geopackage_test.go, ogc/features/datasources/geopackage/metadata.go, ogc/features/datasources/geopackage/stmtcache.go, ogc/features/datasources/geopackage/warmup.go, ogc/features/domain/cursor.go, ogc/features/domain/cursor_test.go, ogc/features/main.go, ogc/features/main_test.go, ogc/features/testdata/expected_foo_collection.json, ogc/features/testdata/expected_foo_collection_with_cursor.json, ogc/features/testdata/expected_foo_collection_with_limit.json, ogc/features/testdata/expected_multiple_gpkgs_bbox_explicit_wgs84.json, ogc/features/testdata/expected_multiple_gpkgs_bbox_wgs84.json, ogc/features/testdata/expected_multiple_gpkgs_bbox_wgs84_jsonfg.json, ogc/features/testdata/expected_multiple_gpkgs_bbox_wgs84_output_rd.json, ogc/features/testdata/expected_multiple_gpkgs_rd.json, ogc/features/testdata/expected_multiple_gpkgs_wgs84.json, ogc/features/url.go, ogc/features/url_test.go, ogc/tiles/main.go, viewer/cypress/fixtures/pdokwegdelen.json
https://dev.kadaster.nl/jira/browse/PDOK-16151
- Bugfix
- Refactor
=> Change cursor encoding to avoid accidental reset of cursor to first page

ogc/features/domain/cursor.go, ogc/features/domain/cursor_test.go, ogc/features/testdata/expected_multiple_gpkgs_wgs84.json
https://dev.kadaster.nl/jira/browse/PDOK-16151
- Bugfix
=> Change to RawURLEncoding

engine/testdata/config_multiple_ogc_apis_single_collection.yaml, engine/testdata/expected_multiple_ogc_apis_single_collection.json, ogc/features/datasources/geopackage/asserts.go, ogc/features/testdata/config_benchmark.yaml, ogc/features/testdata/config_features_multiple_gpkgs.yaml
=> Assert temporal columns are included in the spatial index if configured

ogc/features/templates/features.go.html
=> Only show reference date picker when collection has temporal filtering configured

ogc/common/geospatial/templates/collections.go.html
=> Fix collections page

ogc/common/geospatial/templates/collection.go.html
=> Fix collection page template

engine/templates/openapi/README.md, engine/templates/openapi/tiles.go.json
=> Remove datetime param from Tiles spec, update README

engine/templates/openapi/features.go.json, ogc/features/templates/features.go.html
=> Small UI fixes

engine/templates/openapi/features.go.json
=> Add required parameter with unsupported message

ogc/common/geospatial/templates/collection.go.html, ogc/features/templates/feature.go.html, ogc/features/templates/features.go.html, ogc/features/testdata/expected_straatnaam_silodam.html
The following pages weren't responsive, now they are:
- collection
- features (also fixed overlapping next/prev buttons)
- feature
=> Rewrite HTML to make features page responsive

engine/contentnegotiation.go, ogc/tiles/main.go, ogc/tiles/main_test.go
https://dev.kadaster.nl/jira/browse/PDOK-15727
- Bugfix
=> Fix retrieval of tile using accept-header

examples/config_all.yaml, examples/resources/dummy-style.json, ogc/styles/main.go, ogc/styles/main_test.go, ogc/styles/templates/styleMetadata.go.json, ogc/styles/templates/styles.go.html, ogc/styles/templates/styles.go.json, ogc/styles/testdata/config_minimal_styles.yaml, ogc/styles/testdata/resources/default.json
https://dev.kadaster.nl/jira/browse/PDOK-15750
- Refactor
=> Implement separate styles for each supported projection

examples/resources/dummy-style.json, ogc/styles/main.go, ogc/styles/main_test.go, ogc/styles/testdata/config_minimal_styles.yaml, ogc/styles/testdata/resources/default.json
https://dev.kadaster.nl/jira/browse/PDOK-15750
=> Add zoomlevel range to style JSON

ogc/styles/templates/styles.go.html, ogc/tiles/templates/tiles.go.html
https://dev.kadaster.nl/jira/browse/PDOK-15750
- Bugfix
=> Fix styles dropdown logic and fix alignment issue

config/config.go
een paar extra optional markers in de Config
=> mark some fields as optional in Config

config/config.go
omit empty slice in marshalling interval
=> omit empty slice in marshalling interval

config/config.go
remove uniqueItems openapi validation
not supported by k8s
=> remove uniqueItems openapi validation

config/config.go, config/zz_generated.deepcopy.go, ogc/styles/main_test.go, ogc/tiles/main_test.go, ogc/tiles/templates/tiles.go.html
add config.TilesType for openapi enum validation
=> add config.TilesType for openapi enum validation

config/config.go
add yaml/json omitempty for all optionals
=> add yaml/json omitempty for all optionals

engine/templates/openapi/3dgeovolumes.go.json
https://kadaster.atlassian.net/browse/PDOK-16117
=> Differentiate between implicit and explicit tiling

engine/engine.go
https://kadaster.atlassian.net/browse/PDOK-16117
- Bugfix
=> Fix body close error

assets/i18n/active.en.toml, assets/i18n/active.nl.toml
https://kadaster.atlassian.net/browse/PDOK-16132
=> Small textual changes

viewer/cypress/feature-view-test.cy.ts, viewer/cypress/fixtures/amsterdam-epsg4258.json, viewer/src/app/mapprojection.ts
Definition of projection epsg;4258 was wrong
=> bug solved epsg 4258

internal/engine/router_test.go
https://kadaster.atlassian.net/browse/PDOK-16530
=> chore(test): add unit test

examples/config_all.yaml, internal/ogc/styles/templates/styleMetadata.go.html
'Bijgewerkt tot' datum op styleMetadata pagina weergeven in mensvriendelijk formaat
=> Format lastUpdated date on styleMetadata html page

config/config.go, go.mod, hack/crd/go.mod, internal/ogc/features/datasources/geopackage/backend_cloud.go, internal/ogc/features/datasources/geopackage/backend_cloud_windows.go, internal/ogc/features/datasources/geopackage/backend_local.go, internal/ogc/features/datasources/geopackage/geopackage_test.go
Make SQLite "cache_size" pragma configurable which determines how many pages are cached in-memory.
See https://sqlite.org/pragma.html#pragma_cache_size for details.
=> Cache size

examples/config_all.yaml, internal/ogc/styles/templates/styleMetadata.go.html
https://kadaster.atlassian.net/browse/PDOK-16551
=> Keywords in style metadata html page

internal/engine/templates/layout.go.html
Open the link under the `Datasets` in the same tab
- Refactoring
=> refactor: open datasets link in same tab

assets/i18n/en.yaml, assets/i18n/nl.yaml, go.mod, hack/crd/go.mod, internal/engine/testdata/expected_multiple_ogc_apis_single_collection.html, internal/ogc/common/geospatial/templates/collection.go.html
Restyle HTML collection page
- New feature
=> feat(html): restyle collection HTML page

internal/ogc/features/domain/spatialref.go, internal/ogc/features/domain/spatialref_test.go, internal/ogc/features/json.go, internal/ogc/features/main.go, internal/ogc/features/main_test.go, internal/ogc/features/url.go
=> refactor(srid): Lift CRS/SRS/SRID code to own file

internal/ogc/common/geospatial/templates/collections.go.json, internal/ogc/features/testdata/expected_multiple_feature_tables_single_geopackage.json
Fix https://geoforum.nl/t/wordpress-en-ogc-api-features/9568/5
- Bugfix
-
=> fix(json): Serve correct response for alternate representation.

internal/engine/testdata/expected_multiple_ogc_apis_single_collection.html, internal/ogc/common/geospatial/templates/collection.go.html
=> chore(html): Always open GeoJSON/JSON-FG in new window

internal/ogc/features/domain/profile.go, internal/ogc/features/domain/profile_test.go, internal/ogc/features/main_test.go, internal/ogc/features/testdata/expected_mapsheets_jsonfg.json
Fix relation to wrong collection
=> Feature relations fix

internal/ogc/features/datasources/geopackage/geopackage.go, internal/ogc/features/datasources/geopackage/metadata.go
Make extend columns optional according to gpkg spec.
- Bugfix
=> Allow null values for optional columns in geopackage

internal/ogc/features/url.go, internal/ogc/features/url_test.go
=> feat(features): bbox in features should have surface area

config/config.go
_What_ have you changed and _why_?
- New feature
- Bugfix
- Refactoring
=> fix(tiles): Add more debug info

assets/i18n/en.yaml, assets/i18n/nl.yaml
=> chore(i18n): minor text changes

internal/ogc/features/domain/cursor.go, internal/ogc/features/main.go
Fix for https://github.com/PDOK/gokoala/pull/236
- Bugfix
=> fix(filters): fix sanity check

internal/ogc/common/geospatial/templates/collection.go.html
- Bugfix, found through the rich result testtool on live page
=> fix: add full URL to thumbnail + remove redundant comma.

internal/engine/templates/layout.go.html, internal/engine/testdata/expected_conformance.html, internal/ogc/common/core/templates/conformance.go.html, internal/ogc/common/geospatial/templates/collection.go.html, internal/ogc/features/templates/feature.go.html, internal/ogc/features/templates/features.go.html, internal/ogc/features/testdata/expected_feature_4030.html, internal/ogc/features/testdata/expected_foo_collection_snippet.html, internal/ogc/styles/templates/style.go.html, internal/ogc/styles/templates/styles.go.html, internal/ogc/tiles/templates/tileMatrixSets.go.html, internal/ogc/tiles/templates/tileMatrixSets/EuropeanETRS89_LAEAQuad.go.html, internal/ogc/tiles/templates/tileMatrixSets/NetherlandsRDNewQuad.go.html, internal/ogc/tiles/templates/tileMatrixSets/WebMercatorQuad.go.html, internal/ogc/tiles/templates/tiles.go.html, internal/ogc/tiles/templates/tiles/EuropeanETRS89_LAEAQuad.go.html, internal/ogc/tiles/templates/tiles/NetherlandsRDNewQuad.go.html, internal/ogc/tiles/templates/tiles/WebMercatorQuad.go.html, tests/cypress.config.ts, tests/cypress/e2e/common.cy.ts, tests/cypress/e2e/features.cy.ts, tests/cypress/e2e/styles.cy.ts, tests/cypress/e2e/tiles.cy.ts, tests/cypress/support/e2e.ts, tests/package-lock.json, tests/package.json
=> test: add e2e HTML validation tests

internal/engine/templates/layout.go.html
=> fix: Open Graph url

internal/engine/templates/layout.go.html, internal/ogc/common/geospatial/templates/collection.go.html
=> fix: reorder meta tags, since some tools can't seem to detect the open graph tags

cmd/main_test.go, internal/engine/testdata/expected_multiple_ogc_apis_single_collection.json, internal/engine/testdata/expected_multiple_ogc_apis_single_collection_json_ld.html, internal/ogc/common/geospatial/templates/collection.go.html, internal/ogc/common/geospatial/templates/collection.go.json, internal/ogc/common/geospatial/templates/collections.go.json
add some fields to collection json
- preview/thumbnail
- updated date on links
- keywords
PDOK-16665
=> add some fields to collection json

config/config.go, examples/config_all.yaml, internal/engine/templates/layout.go.html, internal/engine/testdata/expected_dataset_landingpage.json, internal/ogc/common/core/templates/landing-page.go.html, internal/ogc/tiles/main.go, tests/.gitignore, tests/cypress/e2e/common.cy.ts, tests/cypress/e2e/features.cy.ts, tests/cypress/e2e/styles.cy.ts, tests/cypress/e2e/tiles.cy.ts, tests/cypress/support/commands.ts
Fix broken link https://api.pdok.nl/brt/top10nl/ogc/v1/collections//tiles/NetherlandsRDNewQuad?f=json
Also:
+ add extra tests to check for broken links on every page
+ some polishing
=> fix: broken link on tiles metadata page (+ some extras)

Dockerfile, cmd/main_test.go, config/collections.go, config/config.go, config/config_test.go, config/ogcapi_styles.go, config/validators.go, examples/README.md, examples/config_3d.yaml, internal/engine/testdata/config_collections_order_alphabetic.yaml, internal/engine/testdata/config_collections_order_alphabetic_titles.yaml, internal/engine/testdata/config_collections_order_literal.yaml, internal/engine/testdata/config_collections_unique.yaml, internal/engine/testdata/config_multiple_ogc_apis_single_collection.yaml, internal/engine/testdata/expected_multiple_ogc_apis_single_collection.html, internal/engine/testdata/expected_multiple_ogc_apis_single_collection.json, internal/engine/testdata/expected_multiple_ogc_apis_single_collection_json_ld.html
restrict the collection (and style) ID format. lowercase, digits, hyphen and underscore are the only allowed chars
PDOK-17366
=> restrict collection ID format

config/collections.go, config/config_test.go, config/ogcapi_styles.go, config/validators.go, internal/engine/testdata/config_invalid_collection_ids.yaml, internal/engine/testdata/config_valid_collection_ids.yaml
Followup fix for https://github.com/PDOK/gokoala/pull/263
- Bugfix
=> fix: for https://github.com/PDOK/gokoala/pull/263 to also support collection IDs with quotes

.github/workflows/codeql.yml
Setup GitHub built-in linter: CodeQL for Go and Javascript/Typescript, which is focussed on security issues: https://codeql.github.com/
- Linting
=> chore: add CodeQL linting

internal/ogc/tiles/main.go
_What_ have you changed and _why_?
Remove superfluous logging
- Refactoring
=> refactor(tiles): remove superfluous logging of tms limit errors

config/ogcapi_tiles.go, internal/engine/health.go
_What_ have you changed and _why_?
- New feature
- Bugfix
- Refactoring
=> ninja fix: disable tiles healthcheck for now

assets/i18n/nl.yaml, config/config.go, go.mod, hack/crd/go.mod, internal/engine/engine.go, internal/engine/resources.go, internal/engine/resources_test.go, internal/engine/templates/openapi/common-collections.go.json, internal/engine/testdata/config_multiple_ogc_apis_single_collection.yaml, internal/engine/testdata/expected_multiple_ogc_apis_single_collection.html, internal/ogc/common/geospatial/templates/collection.go.html, internal/ogc/features/datasources/geopackage/asserts.go, internal/ogc/styles/main.go, internal/ogc/styles/main_test.go, internal/ogc/styles/templates/styleMetadata.go.html
Major:
- Rework https://github.com/PDOK/gokoala/pull/294 to also handle non-local resources
Minor:
- Fix OpenAPI issue
- Fix asserts on multi-column indexes
- Typo's
- Add full Go toolchain version
- Bug fixes
=> fix: correct legend proxying + various minor issues

internal/ogc/features/domain/schema.go, internal/ogc/features/domain/schema_test.go, tests/cypress/support/commands.ts, viewer/angular.json
=> chore: minor improvements

internal/ogc/features/datasources/geopackage/metadata.go
prevent invalid OpenAPI enum values derived from GeoPackage.
=> feat: prevent invalid OpenAPI enum values derived from GeoPackage.

README.md, cmd/main.go, config/theme.go, internal/engine/templates/layout.go.html, internal/engine/testdata/test_theme.yaml, themes/pdok/includes/dummy.html, themes/pdok/theme.yaml
Added the option to inject html from within your theme files.
=> Tracking support in theme

README.md, config/collections.go, internal/ogc/features/datasources/common.go, internal/ogc/features/datasources/common/README.md, internal/ogc/features/datasources/common/common.go, internal/ogc/features/datasources/common/common_test.go, internal/ogc/features/datasources/common/mapper.go, internal/ogc/features/datasources/common/mapper_test.go, internal/ogc/features/datasources/common/rows.go, internal/ogc/features/datasources/geopackage/asserts.go, internal/ogc/features/datasources/geopackage/geopackage.go, internal/ogc/features/datasources/geopackage/geopackage_test.go, internal/ogc/features/datasources/geopackage/metadata.go, internal/ogc/features/datasources/geopackage/rows.go, internal/ogc/features/datasources/geopackage/sqllog.go, internal/ogc/features/datasources/geopackage/sqllog_test.go, internal/ogc/features/datasources/geopackage/warmup.go, internal/ogc/features/datasources/postgres/asserts.go, internal/ogc/features/datasources/postgres/metadata.go, internal/ogc/features/datasources/postgres/postgres.go, internal/ogc/features/datasources/postgres/rows.go, internal/ogc/features/datasources/postgres/sqllog.go, internal/ogc/features/datasources/postgres/sqllog_test.go, internal/ogc/features/datasources/sqllog.go, internal/ogc/features/datasources/sqllog_test.go, internal/ogc/features/domain/relation.go
Provide common package for shared code between geopackage and postgres datasource
- Refactoring
=> refactor: package for shared code between geopackage and postgres datasource

config/theme.go, internal/engine/themes.go, tests/cypress/e2e/common.cy.ts, tests/cypress/support/commands.ts
Fixed an issue where the basetheme didn't load properly
- Bugfix
- Refactoring
=> fix: basetheme didn't load properly
