- engine/config.go
- ogc/tiles/main.go
- ogc/tiles/main_test.go
- ogc/tiles/testdata/config_minimal_tiles_2.yaml
De tileserver (t-rex) genereert x/y cq col/row, niet row/col zoals in ogc api spec. Dus swappen.
https://dev.kadaster.nl/jira/browse/PDOK-15415
- Bugfix
> swap row/col for tile server

- ogc/tiles/templates/tiles/NetherlandsRDNewQuad.go.html
- webcomponents/vectortile-view-component/README.md
- webcomponents/vectortile-view-component/src/index.html
Ik had xy-swap al uitgezet. Misschien wordt de string `"false"` nog als true gezien?
https://dev.kadaster.nl/jira/browse/PDOK-15415
> disable more xy-swap

- .github/workflows/tidy.yml
- assets/i18n/active.nl.toml
- go.mod
- ogc/features/domain/domain.go
- ogc/features/json.go
> Disable json escape

- .github/workflows/test.yml
- engine/config.go
- engine/config_test.go
- engine/contentnegotiation.go
- engine/engine.go
- engine/templates/openapi/3dgeovolumes.go.json
- examples/config_3d.yaml
- ogc/common/geospatial/templates/collection.go.html
- ogc/common/geospatial/templates/collection.go.json
- ogc/common/geospatial/templates/collections.go.json
- ogc/features/datasources/geopackage/backend_cloud.go
- ogc/geovolumes/main.go
- ogc/geovolumes/main_test.go
- ogc/geovolumes/testdata/config_dtm.yaml
Add support for a Quantized Mesh DTM (Digital Terrain Model) collection to OGC API 3D GeoVolumes
https://dev.kadaster.nl/jira/browse/PDOK-15712
-
> Add support for a Quantized Mesh DTM (Digital Terrain Model)

- ogc/common/geospatial/templates/collection.go.json
- ogc/common/geospatial/templates/collections.go.json
https://api.pdok.nl/kadaster/3d-basisvoorziening/ogc/v1_0-preprod/collections/digitaalterreinmodel?f=json contained 3dtiles instead of DTM reference.
- Bugfix
> Fix content section of 3d GeoVolumes collection: should also include DTM

- ogc/features/domain/cursor.go
- ogc/features/domain/cursor_test.go
- ogc/features/domain/features.go
Make sure decoding doesn't fail when checksum contains cursor separator.
> Handle (theoretical) cursor encoding corner case

- ogc/features/templates/feature.go.html
- viewer/src/app/feature-view/feature-view.component.ts
- viewer/src/index.html
Do not show bounding box select button on the single feature (item) html page 
extra option  show-bounding-box-button added with default value true 
<app-feature-view   show-bounding-box-button="false">
removed this bottom from view
> no bounding box button on map in single item in feature html

- config/config.go
- config/config_test.go
- engine/contentnegotiation.go
- engine/engine.go
- engine/engine_test.go
- engine/openapi.go
- engine/openapi_test.go
- engine/template.go
- ogc/common/core/main_test.go
- ogc/common/geospatial/main_test.go
- ogc/features/datasources/geopackage/asserts.go
- ogc/features/datasources/geopackage/backend_cloud.go
- ogc/features/datasources/geopackage/backend_cloud_darwin.go
- ogc/features/datasources/geopackage/backend_cloud_windows.go
- ogc/features/datasources/geopackage/backend_local.go
- ogc/features/datasources/geopackage/geopackage.go
- ogc/features/datasources/geopackage/geopackage_test.go
- ogc/features/datasources/geopackage/metadata.go
- ogc/features/datasources/geopackage/warmup.go
- ogc/features/html.go
- ogc/features/main.go
- ogc/features/openapi.go
- ogc/features/openapi_test.go
- ogc/features/url.go
- ogc/features/url_test.go
- ogc/geovolumes/main.go
- ogc/processes/main.go
- ogc/styles/main_test.go
- ogc/tiles/main_test.go
move `engine.Config` to its own package in order to use it in the ogcapi-operator.
adding openapi/kubebuilder markers will be done in a next PR
- Refactor
> move Config to its own package

- go.mod
- go.sum
- ogc/features/datasources/geopackage/backend_cloud.go
This fixes "unable to open database file" errors. This was a concurrency issue that manifests itself only under high load, when multiple GeoPackages are in use and property filters are applied.
> Use unique VFS name for each GeoPackage.

- config/config.go
- config/duration.go
- config/duration_test.go
- config/language.go
- config/url.go
- config/url_test.go
- use value receiver for marshal* funcs
- add Config.UnmarshalJSON 
- move local dir validation out of config unmarshalling
- Bugfix
> unmarshal fixes

- config/config.go
- config/config_test.go
fix json marshal inline
zover ik kan lezen / bemerken werkt json inline alleen als de structs embedded zijn
- Bugfix
> fix json marshal inline

- config/config.go
`Extent.Srs` did not have the `omitempty` keyword on the `yaml` and `json` tags, which other `+optional` fields do.
> chore(config): consistent use of omitempty in yaml and json tags

- examples/docker-compose-features-azure.yaml
fix docker-compose using `azurite-seed` exit code instead of `smoke-test`
- Bugfix
> fix: e2e docker-compose exit too soon

- internal/ogc/common/geospatial/templates/collections.go.json
- internal/ogc/features/testdata/expected_multiple_feature_tables_single_geopackage.json
Like in https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#9-example-
> fix(spec): add license link to /collections (was only on landing page).

- go.mod
- hack/crd/go.mod
- internal/engine/templates/layout.go.html
- internal/ogc/features/main.go
This issue caught our attention since we configured a single datasource to a remote/downloadable gpkg but noticed the gpkg was downloaded for EACH collection.
- Bugfix
> Duplicate datasource connections

- internal/ogc/features/templates/feature.go.html
- internal/ogc/features/templates/features.go.html
- viewer/README.md
- viewer/src/app/feature-view/boxcontrol.ts
- viewer/src/app/feature-view/fullboxcontrol.ts
- Missed feature page, also display download url there
- When viewer is in auto mode, and the user uses the next/prev link the viewer breaks. Fixed this.
- Minor change
- Bug fix
> fix(html): Also add link on feature page + fix viewer when using next/prev in auto mode

- .github/workflows/test-go.yml
- internal/engine/problems.go
- internal/ogc/features/datasources/geopackage/geopackage.go
- internal/ogc/features/main.go
- internal/ogc/features/main_test.go
- internal/ogc/features/testdata/config_features_short_query_timeout.yaml
- internal/ogc/features/testdata/expected_empty_feature_collection.json
- internal/ogc/features/testdata/expected_query_timeout_feature.json
- internal/ogc/features/testdata/expected_query_timeout_features.json
Long query's should return an error instead of empty result.
- Bugfix
> fix(sql): return error on query timeout instead of empty result

- config/config.go
- internal/ogc/common/core/templates/conformance.go.html
- internal/ogc/common/core/templates/conformance.go.json
- internal/ogc/common/core/templates/landing-page.go.html
- internal/ogc/common/core/templates/landing-page.go.json
- internal/ogc/tiles/main.go
- fix landing/conformance page to not include dataset tiles when only using collection-level tiles
- made some fields optional in CRD, since we're inlining a struct in the generated YAML/JSON.
- Bugfix
> fix(tiles): few fixes around collection-level OGC API Tiles:

- config/config.go
- config/config_test.go
- internal/engine/problems.go
- internal/engine/testdata/config_invalid_geodatatiles.yaml
- internal/ogc/tiles/main.go
- internal/ogc/tiles/main_test.go
Fix proxying of collection-level tiles
- Bugfix
> fix(tiles): fix proxying of collection-level tiles

- config/config.go
- examples/config_all.yaml
- internal/engine/templatefuncs.go
- internal/ogc/features/main_test.go
- internal/ogc/features/templates/feature.go.html
- internal/ogc/features/templates/features.go.html
- internal/ogc/features/testdata/config_features_webconfig.yaml
- internal/ogc/features/testdata/expected_webconfig_hyperlink_snippet.html
Linkify properties
- New feature
> feat(html): Optionally create hyperlinks of URLs in feature properties

- config/collections.go
- config/config.go
- config/ogcapi_3dgeovolumes.go
- config/ogcapi_features.go
- config/ogcapi_processes.go
- config/ogcapi_styles.go
- config/ogcapi_tiles.go
Refactoring to split config/structs in serveral files (per ogc building block). `config.go` became a bit too long.
- Refactoring
> refactor(config): Split config in several files.

- .github/workflows/test-go.yml
- config/README.md
- config/collections.go
- config/config.go
- config/config_test.go
- config/ogcapi_features.go
- config/zz_generated.deepcopy.go
- internal/engine/testdata/config_collections_order_alphabetic.yaml
- internal/engine/testdata/config_collections_order_alphabetic_titles.yaml
- internal/engine/testdata/config_collections_order_literal.yaml
- internal/engine/testdata/config_collections_unique.yaml
Add option to specify collection ordering
- New feature
- Some refactoring (moving funcs)
> feat(config): Add option to specify collection ordering

- .github/workflows/test-go.yml
- internal/ogc/features/datasources/datasource.go
- internal/ogc/features/main.go
- internal/ogc/features/url.go
- internal/ogc/features/url_test.go
Instead of having both "configurePropertyFiltersWithAllowedValues" and "getConfiguredPropertyFilters".
- Refactoring
> refactor(filters): Consolidate property filters logic to a single func.

- config/collections.go
- hack/crd/go.mod
- hack/crd/go.sum
- internal/engine/templatefuncs.go
- internal/engine/templatefuncs_test.go
Fixes for https://github.com/PDOK/gokoala/pull/235 and https://github.com/PDOK/gokoala/pull/229
- Bugfix
> Fixes linking and sorting

- internal/ogc/tiles/main.go
Fix broken link to JSON representation of collection-level tiles
- Bugfix
> fix(tiles): Fix broken link to JSON representation of collection-level tiles

- config/collections.go
- config/ogcapi_features.go
- internal/ogc/features/datasources/geopackage/geopackage.go
- internal/ogc/features/domain/mapper.go
- internal/ogc/features/domain/mapper_test.go
- internal/ogc/features/main.go
- reduce chance of timeouts by finetuning RTree/BTree threshold
- when timeout occurs return proper error (also included row mapping)
- Bugfix
> perf: rtree/btree threshold, reduce from 30K to 8K + fix timeout handling

- internal/ogc/features/datasources/geopackage/metadata.go
When comparing collections to the `gpkg_contents` table, compare the collection's `ID` or `TableName` against the `table_name`
column instead of the `identifier` column, as the latter may contain a human-readable text (shorter, or including punctuation).
- Bugfix
> fix(gpkg): check table_name instead of identifier

- internal/ogc/common/core/templates/landing-page.go.html
When a long list of keywords was supplied, the word-wrap caused breaking of keywords in arbitrary places, often in the middle of words. This is fixed by using Bootstrap's `.text-break` class.
- Bugfix
> fix(html): avoid wrapping keywords in the middle of a word

- viewer/src/app/feature-view/feature-view.component.ts
fix viewer shouldnt convert url to lowercase
e.g. collection IDs are case sensitive and sometimes contain upper case chars
PDOK-17366
- Bugfix
> fix viewer shouldnt convert url to lowercase

- internal/ogc/features/domain/props.go
put href prop before _shortest_ similarly named key
PDOK-17329
> put href prop before _shortest_ similarly named key

- internal/ogc/common/geospatial/templates/collection.go.html
Same as landing page, keywords are breaking incorrectly on the collection overview page.
- Bugfix
> fix(html): correctly break keywords on collection page

- internal/ogc/styles/templates/styles.go.html
Fixes [https://github.com/PDOK/gokoala/security/code-scanning/2](https://github.com/PDOK/gokoala/security/code-scanning/2)
To fix the problem, we need to ensure that any user input is properly sanitized or escaped before being used in the DOM. In this case, we should escape the `selectedStyle` variable before using it to construct the URL. This can be done using a function that ensures any special characters are properly encoded.
We will use JavaScript's `encodeURIComponent` function to escape the `selectedStyle` and `selectedProjection` values before using them in the URL.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 2: DOM text reinterpreted as HTML

- .github/workflows/e2e-test.yml
- cmd/main_test.go
- examples/config_all.yaml
- internal/engine/contentnegotiation.go
- internal/engine/templates/openapi/tiles.go.json
- internal/engine/testdata/expected_sitemap.xml
- internal/ogc/tiles/main.go
- internal/ogc/tiles/main_test.go
- internal/ogc/tiles/templates/tiles.go.json
- internal/ogc/tiles/testdata/expected_collection_level_tiles.json
- internal/ogc/tiles/testdata/expected_top_level_tiles.json
- internal/ogc/tiles/tileMatrixSetLimits/EuropeanETRS89_LAEAQuad.yaml
- internal/ogc/tiles/tileMatrixSetLimits/NetherlandsRDNewQuad.yaml
- internal/ogc/tiles/tileMatrixSetLimits/WebMercatorQuad.yaml
- Add `tileMatrixSetLimits` to `/tiles`
- Add `tileMatrixSetURI` to `/tiles` for registered TileMatrixSets
- Correct `operationId` suffixes in `/api`
- Return HTTP 404 instead of HTTP 204 on out of bounds requests
- Add e2e-test for OGC API Tiles conformance
- New feature
- Bugfix
- Refactoring
> fix: for OGC API Tiles validator findings [merge in januari]

- internal/ogc/tiles/main.go
Breadcrumb for `/tiles/<tileMatrixSetId>` had an incorrect path, resulting in 404s.
- Bugfix
> fix: correct path for tiles metadata breadcrumb, fixes JSON link

- config/config.go
- config/ogcapi_tiles.go
- internal/engine/health.go
Add guard clause for the eventuality that `Collection.Tiles` struct is nil, refactor `newHealthEndpoint()` to fallback to basic endpoint when this occurs.
- Bugfix
- Refactoring
> fix: re-enable tiles healthcheck

- config/ogcapi_features.go
- config/ogcapi_tiles.go
Inlining only works on embedded structs, this caused issues in the`ogcapi-operator`. Added specific JSON marshalling functions for the offending structs to avoid the issue.
- Bugfix
- Refactoring
> fix: add custom JSON marshalling for inline structs

- config/config.go
- config/config_test.go
- config/ogcapi_tiles.go
- internal/engine/testdata/config_invalid_tiles_projection.yaml
Add validation on configured Tiles projections, fail on unsupported projections. As a result of #287.
- New feature
> feat(config): add validation on configured tiles projections

- internal/ogc/tiles/templates/tiles/EuropeanETRS89_LAEAQuad.go.tilejson
- internal/ogc/tiles/templates/tiles/NetherlandsRDNewQuad.go.tilejson
- internal/ogc/tiles/templates/tiles/WebMercatorQuad.go.tilejson
Render zoom level 11 correctly in TileJSON 
- Bugfix
> fix: render zoom level 11 correctly in TileJSON.

- internal/engine/types/date.go
- internal/engine/types/date_test.go
- internal/engine/types/util.go
- internal/ogc/features/datasources/geopackage/geopackage.go
- internal/ogc/features/datasources/geopackage/metadata.go
- internal/ogc/features/domain/mapper.go
- internal/ogc/features/domain/mapper_test.go
- internal/ogc/features/domain/schema.go
- internal/ogc/features/templates/schema.go.html
- tests/cypress/support/commands.ts
map date columns (= without time component) as actual dates, not timestamps with the time set to zero.
- Bug fix
- Potential breaking change
> fix: map date columns (= without time component) as actual dates, not timestamps with the time set to zero.

- Dockerfile
- internal/ogc/features/datasources/datasource.go
- internal/ogc/features/datasources/geopackage/geopackage.go
- internal/ogc/features/datasources/geopackage/geopackage_test.go
- internal/ogc/features/datasources/geopackage/metadata.go
- internal/ogc/features/datasources/postgis/postgis.go
- internal/ogc/features/datasources/postgis/postgis_test.go
- internal/ogc/features/domain/schema.go
- internal/ogc/features/domain/spatialref.go
- internal/ogc/features/feature.go
- internal/ogc/features/features.go
- internal/ogc/features/main.go
- internal/ogc/features/proj.go
- internal/ogc/features/proj_test.go
Swap XY to YX when a certain CRS for a configured datasource (eg. geopackage) requires this. Uses `proj` to determine axis order. For example relevant when serving features in EPSG:4258.
- Bugfix
> fix: swap xy when required

- internal/ogc/features/datasources/geopackage/metadata.go
- internal/ogc/features/domain/mapper.go
fix: read schema only on feature tables that belong to collections. Ignore tables that aren't configured as a collection (but do log these)
- Bugfix
> fix: read schema only on feature tables that belong to collections

- internal/ogc/features/datasources/geopackage/geopackage.go
- internal/ogc/features/features_test.go
- internal/ogc/features/testdata/expected_features_properties_order.html
https://github.com/PDOK/gokoala/pull/322 didn't work as expected when `properties` and `propertiesExcludeUnknown` was in use. This PR fixes that.
- Bugfix
> fix: column ordering, and fix overwrite of geom swapcoords by "select *"

- viewer/package-lock.json
- viewer/package.json
- Security patch for CVE-2025-54313. GoKoala is not affected, just to make sure.
> chore: preventive patch for eslint-config-prettier

- internal/engine/openapi.go
- internal/ogc/features/feature_test.go
- internal/ogc/features/features_test.go
- internal/ogc/features/schema_test.go
- internal/ogc/features/setup_test.go
In Go, tests in different packages run in parallel automatically. This enabled parallel tests WITHIN the features package since this package contains a lot of tests.
- Test performance improvement
> perf: run tests within the ogc/features package in parallel

- .golangci.yaml
- config/config.go
- config/duration.go
- config/mediatype.go
- config/url.go
- internal/ogc/features/datasources/geopackage/encoding/geopackage_test.go
Specifically avoid disabling all revive rules by tweaking the var-naming rule
> chore: tweak golangci-lint after migrating from v1 to v2.
